### ISSUE TITLE
Issue setting up SurfaceHub with Exchange on O365-D

### ISSUE THREAD

**Issue by sub2d** [Microsoft/windows-itpro-docs#104]
Environment has one unique SIP and multiple SMTP domain. UPNs match SMTP domain. Everything was setup as described in guide only part that was not working was Exchange. After [checking connectivity](https://testconnectivity.microsoft.com/) for Exchange ActiveSync Autodiscover we found following URI.
"https://exchange.contoso.com/Microsoft-Server-ActiveSync".

After adding this part exchange was setup correctly and device was able to access calendar.

![image](https://cloud.githubusercontent.com/assets/17128563/21849458/259d904a-d806-11e6-84c5-1ff27f9acaa8.png)

**Comment by jdeckerMS** [comment]
Thanks for providing this information. I'll pass it on to the engineering team to investigate if changes to the topic are needed. Sorry that I can't provide an estimate for when any changes will be made.

**Comment by jdeckerms** [comment]
I'm still working on getting a resolution for this issue.

**Comment by jdeckerms** [comment]
The Surface Hub documentation will be updated in the near future for the Windows 10, version 1703 release. Please let us know if the new docs don't address the issue adequately.
