### ISSUE TITLE
Can't remove start menu customisation

### ISSUE THREAD

**Issue by NJArcher** [Microsoft/windows-itpro-docs#105]
Hi,
When you setup a policy to apply a custom start menu layout then it should be documented how to go back to the default. I've found that once you apply a custom start menu layout then this persists even after the policy has been disabled removing the value  HKCU\Software\Policies\Microsoft\Windows\Explorer!StartLayoutFile.
The only way I can return to the default start menu layout is to delete the local profile or to replace the 
c:\users\<user>\appdata\local\tiledatalayer with one from a user that has the default start menu layout (similar to 
![image](https://cloud.githubusercontent.com/assets/25222944/22105563/7f4e652e-de3c-11e6-8a60-ee086923173b.png))

Can this at least be documented or is there a way I have missed? This was tested on Windows 10 v1511 Education.

Thanks.

**Comment by jdeckerMS** [comment]
Thanks for bringing this to our attention. I'll contact the engineering team to discuss adding guidance for this situation to the documentation.

**Comment by jdeckerms** [comment]
I'm still working on getting a resolution for this issue.

**Comment by jdeckerms** [comment]
NJArcher, there isn't a simpler method to revert a Start layout to default. I'm not adding the method that you found to the topic at this time as there is still an open question as to whether this is a recommended method that we support. But the product team is aware now of the scenario of an admin wanting to return to default and is exploring it. We appreciate you bringing this to our attention!
