### ISSUE TITLE
Significant difference in behavior for "Force a specific default lock screen image" between 1511 and 1607

### ISSUE THREAD

**Issue by loosus456** [Microsoft/windows-itpro-docs#111]
The Windows Spotlight documentation (https://technet.microsoft.com/en-us/itpro/windows/manage/windows-spotlight) states the following:

> Administrators can replace Windows Spotlight with a selected image using the Group Policy setting Computer Configuration > Administrative Templates > Control Panel > Personalization > Force a specific default lock screen image.

In 1511, this Group Policy worked exactly as stated above: it replaced the inbox default lock screen image.  Users could still choose their own lock screen image.

There is a separate policy, **Prevent changing lock screen image**, that can additionally and optionally be used to prohibit users from changing the lock screen image.

In 1607, simply enabling **Force a specific default lock screen image** prohibits users from changing the lock screen image.

This seems like a bug, since (a) there is a separate Group Policy for preventing users from changing the lock screen image, (b) the description text in the Group Policy setting actually mentions that the policy should only change the inbox lock screen image, and (c) this change in behavior is not documented in the web documentation anywhere.

Surely, this new behavior is not intentional, but it's been several months since 1607 was released, and has not been changed even with several cumulative updates, so I am beginning to wonder if it's by design for some bizarre reason.  Can this please be clarified?

For the record, I'm using the Enterprise versions of Windows 10.

**Comment by jdeckerMS** [comment]
I'm checking with the engineering team and will let you know what I learn from them.

**Comment by jdeckerMS** [comment]
Sorry for the delay! I've confirmed that the behavior you're seeing in 1607 is a bug. "Force a specific default lock screen" is not supposed to prevent the user from changing it. This will be fixed in the next feature update.
