### ISSUE TITLE
Seen 4774(F) in the wild

### ISSUE THREAD

**Issue by fluggo** [Microsoft/windows-itpro-docs#113]
I don't have any authoritative information to add, but I can say with certainty that I have seen an event 4774(F) in the wild. The [documentation](https://technet.microsoft.com/en-us/itpro/windows/keep-secure/event-4774) only mentions a success event, and pretty much says it never happens.

Details on the event in the while can be found [here](http://forum.ultimatewindowssecurity.com/Topic7313-282-1.aspx), but the relevant details are:

```
An account was mapped for logon.

Authentication Package:	Schannel
Account UPN:	ACCOUNT@Domain.com
Mapped Name:	ACCOUNT
```

This was an AUDIT_FAILURE, severity ERROR. Task name was "Credential Validation". These events corresponded with audit failure events 6273 (Network Policy Server denied access) and 4771 (Kerberos pre-auth failed) for the same account.

**Comment by Justinha** [comment]
@fluggo thanks for sharing this. I added it to the topic.
