### ISSUE TITLE
Windows Easy Transfer in Windows 10

### ISSUE THREAD

**Issue by toadlife** [Microsoft/windows-itpro-docs#118]
In the docs for the user state migration tool, it says that for a small number of computers the Windows Easy Transfer wizard can be used, but the WETW is not available for Windows 10.

**Comment by greg-lindsay** [comment]
Thanks for catching this! I've updated the topic to indicate that PCmover Express should be used intead, per https://support.microsoft.com/en-us/instantanswers/d4872cf1-5854-a363-2e14-2497f56f1505/windows-easy-transfer-is-not-available-in-windows-10 

The changes will be live tomorrow, 2/3/2017

**Comment by toadlife** [comment]
Thanks. I actually ended up using the User State Migration feature of our SCCM 2012 R2 system. It worked perfectly. I wish I had looked into that feature years ago!
