### ISSUE TITLE
Remote Desktop

### ISSUE THREAD

**Issue by VyacheslavKokorin** [Microsoft/windows-itpro-docs#121]
I can not connect to Azure AD-joined PC. But It says what it's passable in this article https://technet.microsoft.com/en-us/itpro/windows/manage/connect-to-remote-aadj-pc.
The author is Jeanie Decker. I need to ask her about this. Help me please.

**Comment by jdeckerMS** [comment]
Hi, do you have questions or feedback about the topic?

**Comment by VyacheslavKokorin** [comment]
Hello! Yes, I want to say what it doesn't work. I make all settings as you say. Are you sure that it works exactly as you say?

**Comment by jdeckerMS** [comment]
It should work as documented. You can check with your Azure Active Directory administrator to make sure remote connections aren't blocked by any policies, and contact https://support.microsoft.com for support.

**Comment by VyacheslavKokorin** [comment]
It should, but it doesn't not. :(

**Comment by jdeckerMS** [comment]
Please contact https://support.microsoft.com for support.
