### ISSUE TITLE
Win 10 Pro start menu customization issues feedback

### ISSUE THREAD

**Issue by michaellaunch** [Microsoft/windows-itpro-docs#124]
Hi jdeckerMS, 
Re: article: https://technet.microsoft.com/en-au/itpro/windows/manage/customize-windows-10-start-screens-by-using-group-policy

The problem is that us IT Admins trying to administer 500+ staff on Win 10 pro and not having all the options to preset layout for new user and then allow  them to freely rearrange is not currently possible. I would like Microsoft to add group policy settings like in Win 8.1  in gpo: user config > Administrative Templates > Start Menu and Taskbar > "Pin Apps to Start when installed" - it needs to work on Win 10 as well. Can this be flagged as a priority for next version of Win 10 ADMX Templates? 

thanks, 
Michael

**Comment by michaellaunch** [comment]
@jdeckerMS
Thought I check with you.

**Comment by jdeckerMS** [comment]
Hi Michael, this would be a good suggestion to submit using the Feedback Hub in Windows 10. That's the best avenue for feedback on the product.
