### ISSUE TITLE
Code improvement for Hybrid deployment

### ISSUE THREAD

**Issue by gautamsi** [Microsoft/windows-itpro-docs#13]
I see that you suggest provisioning Remote Mailbox from Exchange on-prem, but the code is saying "Enable-Mailbox" it should be "Enable-RemoteMailbox"

this is in windows-itpro-docs / devices / surface-hub / hybrid-deployment-surface-hub-device-accounts.md  step 3 under Exchange on-prem

**Comment by brianlic-msft** [comment]
This has been fixed.  Thanks for reporting!
