### ISSUE TITLE
Missing reference for Windows store App in the taskbar

### ISSUE THREAD

**Issue by Diagg** [Microsoft/windows-itpro-docs#133]
Hi jdeckerMS,

Ref: https://github.com/Microsoft/windows-itpro-docs/blob/master/windows/manage/configure-windows-10-taskbar.md

I just want to stress that an exemple with the Store app pinned to the taskbar is requiered ! If i want to get AUMID of the store app using Export-Startlayout, the AUMID is Microsoft.WindowsStore_8wekyb3d8bbwe!App . 

This AUMID works fine for the start menu but not for the taskbar as it shows a small store icon with a blue background... worse than that, nothing append when you click on it...

I guess that there should be a different AUMID that pin the correct store icon (that one with no background) but i can't find any refences to it!

So, please provide an example in the documenation to every one can pin the store.

Regards

Diagg

**Comment by jdeckerms** [comment]
Hi Diagg, according to the product team, you have the correct AUMID for Store. They said that any app icon will have a background like that if the app is not installed yet, and that clicking the icon will put the app on the top of the installation queue.
