### ISSUE TITLE
This page references 'anti-TPM hammering' but doesn't give figures

### ISSUE THREAD

**Issue by 1RedOne** [Microsoft/windows-itpro-docs#136]
Specifically in this quote

>and all of this must be done before TPM anti-hammer capabilities lock the device. 

No further information is igiven. 

What should be displayed:

* examples of the anti-hammering capabiilties
* default and recommended thresholds for these capabilities

**Comment by DaniHalfin** [comment]
Thanks for the feedback. I've looked into it and it seems like we reference this in 3 different ways - "anti-hammering", "brute-force attack resistance", "dictionary attack logic behavior".
We'll be looking to change all the references to be more consistent. Appreciate you pointing it out to us!

**Comment by DaniHalfin** [comment]
Hi again, after some consideration, we feel like all 3 term have a place in our content. We would be looking to make changes to position anti-hammering as the protection mechanism against brute-force attacks, with dictionary attacks being an elaborate form of a brute-force attack.

Let me know if you have any thoughts or feedback, while we work to edit this into our content.
Again, we appreciate your feedback and thank you for reaching out to us.

**Comment by DaniHalfin** [comment]
We have the changes lined up and ready to go.
A link was added for the anti-hammering term that redirects to the TPM fundamentals page, which contains an explanation about it.
Thanks again for your feedback and don't hesitate to let us know when you feel like our content is lacking. This one required some thinking, but I hope that in the end we got it right.
You should see the change in a day (or two).

**Comment by 1RedOne** [comment]
Thank you, that's a reasonable fix.
