### ISSUE TITLE
Typographic error in UE-V section

### ISSUE THREAD

**Issue by Donny247** [Microsoft/windows-itpro-docs#137]
There is a typographic error in the UEV section. 

Consider replacing this
With the release of Windows 10, version 1607, UE-V is included with the Windows 10 for Enterprise edition. If you are new to Windows 10 and **EU-V** 

With this
With the release of Windows 10, version 1607, UE-V is included with the Windows 10 for Enterprise edition. If you are new to Windows 10 and **UE-V**

**Comment by eross-msft** [comment]
Merging the change from exchange12rocks. Closing this issue.
