### ISSUE TITLE
Start layout XML and Custom LogoURI

### ISSUE THREAD

**Issue by Kazzan** [Microsoft/windows-itpro-docs#138]
There is not statement if Square150x150LogoUri and Wide310x150LogoUri can be set some other file path different from ms-appdata:/// and ms-appx:///.

These are generated by Edge when Site is Pinned, but we want to set different picture.

Also site http://www.buildmypinnedsite.com/ state another size of Tile which can not be set by XML.

And in Arguments are more elements like -formatVersion 0x00000003 -pinnedTimeLow 0x4a25edef -pinnedTimeHigh 0x01d2929c -securityFlags 0x00000000 -tileType 0x00000000 -url 0x00000014 which Edge generate, not only URL of website. There values are not mentioned here.

This should be corrected.

**Comment by jdeckerMS** [comment]
Thanks for your feedback. I'll review your suggestions with the engineering team to see about making changes to the documentation. (www.buildmypinnedsite.com is not a Microsoft property)

**Comment by Kazzan** [comment]
Thanks for reply. It will be nice to make this clear.

And, based on WHOIS records of this domain, it looks like as very Microsoft property of Edge Dev Team.

**Comment by emphasismemorandum** [comment]
Unfortunately energy power outage, unable to overview tech issues. 

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 10, 2017 at 3:47 PM, Jeanie Decker<notifications@github.com> wrote:   
Thanks for your feedback. I'll review your suggestions with the engineering team to see about making changes to the documentation. (www.buildmypinnedsite.com is not a Microsoft property)

**Comment by jdeckerMS** [comment]
Kassan, you're right, I must have looked up the domain ownership incorrectly.

**Comment by Kazzan** [comment]
Elizabeth Ross: Hi, how exactly was my question handled? I do not see any relevant change at https://msdn.microsoft.com/en-us/library/windows/hardware/mt171092(v=vs.85).aspx.

**Comment by jdeckerMS** [comment]
We got your feedback and it's in the work queue, but I can't estimate when a change will be made to the online documentation.
