### ISSUE TITLE
Loading the SchoolSharedPcs app to Windows ICD

### ISSUE THREAD

**Issue by eduardooropeza** [Microsoft/windows-itpro-docs#142]
Has anyone been able to load the SharedPc app to windows ICD without getting errors to add or modify settings/policy's?

**Comment by eduardooropeza** [comment]
Yes sorry I meant the Set up School Pcs App. I am trying to load that Microsoft provision package to Windows ICD to modify certain policy's in it that are disabled such as Biometrics, or Windows Hello, without loosing the policy's already in place or the other customizations such as background and start tiles, or the removal of non educational apps.

**Comment by CelesteDG** [comment]
Are you trying to modify a .ppkg that was created using the Set up School PCs app? When you did this, did you start WICD and then import the .ppkg as a starting point? If you have the raw XML file that was used to generate the .ppkg, you can also just modify the .xml directly (add the settings you do want, remove any that you don't, etc) and use the command-line to generate a new .ppkg out of that starting point.

**Comment by CelesteDG** [comment]
No response. Please close for now. There is an updated "Use Set up School PCs app" topic that might be of help for now: https://docs.microsoft.com/en-us/education/windows/use-set-up-school-pcs-app
