### ISSUE TITLE
Broken Link: Download the complete set of Administrative Template (.admx) files for Windows 10.

### ISSUE THREAD

**Issue by chrber** [Microsoft/windows-itpro-docs#15]
Download the complete set of Administrative Template (.admx) files for Windows 10.

Link is broken

**Comment by brianlic-msft** [comment]
@chrber The link in new-policies-for-windows-10.md seems to be working fine.  Is the file with the broken link?

**Comment by brianlic-msft** [comment]
@chrber The broken link appears to be fixed.  If it happens again, please reopen this issue.  Thanks!
