### ISSUE TITLE
Chassis Types Range Error

### ISSUE THREAD

**Issue by buena44** [Microsoft/windows-itpro-docs#151]
On document : basic-level-windows-diagnostic-events-and-fields.md

"ChassisType Represents the type of device chassis, such as desktop or low profile desktop. The possible values can range between 1 - 24."

But it should be 1 - 36 

Source : https://www.dmtf.org/standards/smbios
Doc: DSP0134	3.1.1

**Comment by brianlic-msft** [comment]
@buena44 This has been fixed.  Thank you for the feedback!
