### ISSUE TITLE
Correct registry key location

### ISSUE THREAD

**Issue by AronParker** [Microsoft/windows-itpro-docs#156]
https://technet.microsoft.com/itpro/windows/configure/manage-connections-from-windows-operating-system-components-to-microsoft-services#certificate-trust-lists

In section "3. Date & Time" it says regarding the registry path:
HKEY_LOCAL_MACHINE\Policies\Microsoft\W32time\TimeProviders\NtpClient!Enabled

However I believe it should be:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\W32time\TimeProviders\NtpClient!Enabled

**Comment by Justinha** [comment]
@AronParker Thanks for the correction. It is published now.

**Comment by AronParker** [comment]
Thanks for the quick fix!
