### ISSUE TITLE
Bitlocker CSP SyncML response is always 406(Optional feature not supported)

### ISSUE THREAD

**Issue by xiaobinkong** [Microsoft/windows-itpro-docs#167]
Hi expert,

Since Windows 10 1703 announced to support Bitlocker CSP, I tried to verify it on my surface pro on which TPM is 2.0.

Before testing the Bitlocker CSP, I have upgraded Surface to 1703 build 15063.138, and set the Bitlocker to on for my OS drive.

Following the CSP specification, I send the Query, Add or Replace SyncML to my system, but all items return 406(Optional feature not supported).  I checked the bitlocker setting via Group Policy Editor, all setting are not configured. My syncML request and device response as attachment, can someone point out if there is any problem? I query and configure other new supported policy such as "Location/EnableLocation" without error. I am not sure if Bitlocker CSP is really supported on 1703 build 15063.138 which is the latest one. 

Thank you in advance!

Eric Kong

[bitlocker_Req_Resp.txt](https://github.com/Microsoft/windows-itpro-docs/files/948132/bitlocker_Req_Resp.txt)

**Comment by eross-msft** [comment]
Hi @xiaobinkong,
This area is for help and questions specifically about the documentation. The best way to get help with the BitLocker functionality would be to contact support (https://support.microsoft.com/en-us/products/windows?os=windows-10). I'd also suggest reading the BitLocker content (https://docs.microsoft.com/en-us/windows/device-security/bitlocker/bitlocker-overview), if you haven't already done so.
