### ISSUE TITLE
Continued use of MS-CHAPv2 while Cred Guard enabled?

### ISSUE THREAD

**Issue by sklynsma** [Microsoft/windows-itpro-docs#197]
In the video on the [Microsoft Virtual Academy website Lesson #5 – Credential Guard Deployment ](https://mva.microsoft.com/en-us/training-courses/deep-dive-into-credential-guard-16651?l=sRcyvLJyC_3304300474) at about 4:45 of the video, the speaker (Seth) states “…if you want to use MS-CHAPv2, the credentials must be supplied by the user or stored in Credential Manager”.  

How is this done exactly?  I support an organization that is heavily reliant on MS-CHAPv2 for their 802.1x authentication.  We do not have an enterprise device Certificate Authority infrastructure so are caught between turning off Credential Guard or turning off 802.1x.

Seth's statement seems to indicate a potential work-around we could use until our Device CA  infrastructure is in place.  All we'd have to do is somehow store the device credentials in Credential Manager.  Then, if I understand Seth's statement correctly, we could use 802.1x/MS-CHAPv2 and Credential Guard together, thus gaining us the security benefits of both capabilities.

I originally posted the question [here](https://trainingsupport.microsoft.com/en-us/tcmva/forum/tcmvacoursefdbk-tcmvawindows/ms-chapv2-and-credential-guard/ba44054b-caab-46f5-b5df-b4998d2d705c) but was told to move it to GitHub so I "can get the answers directly from the course contributors."  Any insights would be greatly appreciated.

**Comment by brianlic-msft** [comment]
The VPN client should provide a way to remember credentials.

**Comment by sklynsma** [comment]
Brian,
This is an 802.1x issue…layer 2.   VPNs have not yet been established….in fact client hasn’t even been granted access to the network yet.

**Comment by brianlic-msft** [comment]
@gitmichiko can you help here?

**Comment by GITMichiko** [comment]
The VPN client application should provide the way to "remember credentials". When a user checks a box or whatever UI is used, then the application should save the credential as a domain type specific to the VPN server targetname so it is protected when Credential Guard is enabled. Or they can simply prompt the user for credentials.

**Comment by sklynsma** [comment]
But VPNs have not yet been established at the moment the supplicant system is plugged into the network.  You are running EAPoL and exchanging device (**not user**) credentials with the nearest network device (which in turn forwards those **device credentials** to a RADIUS policy server/Active Directory service for confirmation that device should be allowed on network).   Only after approval of those **device credentials** does the device gain access to the network and VPN servers on the network.   Certainly then saved **user credentials** may be used to establish VPNs.

**Comment by brianlic-msft** [comment]
@sklynsma If you still have questions, you should contact Microsoft Support.  Thanks!
