### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by sejool** [Microsoft/windows-itpro-docs#2]
There is a error in the XML  code under "Remove default apps and add your own". The path is incorrect:

%APPDATA%Microsoft\Windows\Start Menu\Programs\Accessories\Internet Explorer.lnk

Should be:
%APPDATA%\Microsoft\Windows\Start Menu\Programs\Accessories\Internet Explorer.lnk"

**Comment by brianlic-msft** [comment]
@sejool Thanks for reporting this!  Which markdown file is this in?

**Comment by sejool** [comment]
It's in configure-windows-10-taskbar.md

**Comment by brianlic-msft** [comment]
This is now fixed.  Thanks again for reporting this!
