### ISSUE TITLE
Change in BitLocker PIN Length

### ISSUE THREAD

**Issue by Kazzan** [Microsoft/windows-itpro-docs#200]
Hi, it seems that BitLocker default and minimum length get updated from 4 numbers to 6 numbers. You do not mention that in "What’s new for IT pros in the Windows 10 Creators Update" article. I mean that this is really big change primary for end user experience.

**Comment by Justinha** [comment]
@Kazzan Thanks for the feedback. This was recently added to our docs, see https://docs.microsoft.com/en-us/windows/device-security/change-history-for-device-security  

I'll forward your feedback to the blog owner for What’s new for IT pros in the Windows 10 Creators Update.
