### ISSUE TITLE
Sample Device Guard Policy seems to break Powershell & Server Manager

### ISSUE THREAD

**Issue by Antonlovesdnb** [Microsoft/windows-itpro-docs#218]
The following rule in the sample device guard bypass mitigation policy breaks Powershell & Server Manager on Windows Server 2016 build 14393 

    _<Deny  ID="ID_DENY_SMA"           FriendlyName="System.Management.Automation.dll" FileName="System.Management.Automation.dll" MinimumFileVersion = "10.0.16215.999" />_

**Comment by Justinha** [comment]
@Antonlovesdnb Thanks for reporting this issue. The engineering team believes that applying the quality update that was released this week will resolve this issue. Let us know if you still experience the issue after applying the quality update. 

Thanks,
Justin [MSFT]

**Comment by eross-msft** [comment]
Closing this issue. @Antonlovesdnb, if this doesn't address your issue, please feel free to reactivate. Or, you can create a pull request with the text changes you'd like to see online.

**Comment by Antonlovesdnb** [comment]
dll version after the latest update is 10.0.14393.1378 which is still below the version in the sample configuration posted. Not a huge issue just a general heads up if someone wants to use the configuration file shown here. Thank you for looking into the issue.
