### ISSUE TITLE
Windows Hello deactivated in v1607

### ISSUE THREAD

**Issue by jaegerschnitzel** [Microsoft/windows-itpro-docs#22]
https://technet.microsoft.com/en-us/itpro/windows/keep-secure/implement-microsoft-passport-in-your-organization

"The Group Policy setting Turn on PIN sign-in does not apply to Windows Hello for Business. It still prevents or enables the creation of a convenience PIN for Windows 10. Use Windows Hello for Business policy settings to manage PINs."

This is not true! There is an error in v1607 and all options are greyed out:
https://social.technet.microsoft.com/Forums/getfile/922874

If I change the registry according to these settings, it's working:
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System]
„AllowDomainPINLogon“=dword:00000001

Unfortunately the corresponding group policy is only working in Windows 8.1.

Can you please fix this problem?
You can find more information here: https://social.technet.microsoft.com/Forums/windows/en-US/b975932a-b50b-4759-b43a-c94854c6da83/cant-enable-windows-hello-with-fresh-install-of-anniversity-upgrade-on-domain-account?forum=win10itprosetup

**Comment by brianlic-msft** [comment]
The documentation has been updated.  Thanks!
