### ISSUE TITLE
Backup BitLocker Recovery Keys from TPM to AD missing in 1607

### ISSUE THREAD

**Issue by Kazzan** [Microsoft/windows-itpro-docs#27]
Hello, based on recet technical problems with TPM activation after upgrade to 1607 issue about not working backup of BitLocker recovery keys to AD is not working in 1607, because GPO is missing in new templates. Based on threads TechNet [Forums like Turn on TPM Backup to Active Directory Domain Services](https://social.technet.microsoft.com/Forums/windowsserver/en-US/c8ad5825-ecc7-4873-a2c0-d6b51789e12e/turn-on-tpm-backup-to-active-directory-domain-services?forum=winserverGP) is there a question, if this function was truly removed to MBAM? If yes, why [What's new in Windows 10, version 1607](https://technet.microsoft.com/en-us/itpro/windows/whats-new/whats-new-windows-10-version-1607) is missing this information? Thanks for clarification.

**Comment by jaegerschnitzel** [comment]
That's the third big issue with v1607 group policies. And Microsoft still doesn't comment...
It seems as if the right hand doesn't know what the left hand is doing.

**Comment by Kazzan** [comment]
I found [this article](https://blogs.technet.microsoft.com/supportingwindows/2016/09/15/group-policy-templates-admx-removed-in-windows-10-and-windows-server-2016/) that talking about this change and that it is not related. But all previous guides to set it up, talking about this GPO.

**Comment by brianlic-msft** [comment]
This GPO was removed in Windows 10, version 1607, but it doesn't affect BitLocker recovery keys.  @Kazzan, thanks for sharing that link!  It lists the policies that were removed in Windows 10, version 1607 and some notes on why it was done.

**Comment by stoinov** [comment]
I came across [this answer](https://superuser.com/questions/1104810/clearing-tpm-does-not-ask-for-new-password-but-change-owner-password-asks-for), that might shed some light why this was removed.
And [here is](https://docs.microsoft.com/en-us/windows/device-security/tpm/change-the-tpm-owner-password) the detailed explanation by Microsoft on this change.
