### ISSUE TITLE
Show private store only on windows 10 mobile devices - description incomplete

### ISSUE THREAD

**Issue by imfgmbh** [Microsoft/windows-itpro-docs#37]
On TechNet articles like [https://technet.microsoft.com/de-de/itpro/windows/manage/manage-access-to-private-store](https://technet.microsoft.com/de-de/itpro/windows/manage/manage-access-to-private-store) you'll find steps to show private store only in the Windows 10 app store. In contrast to description, the steps provided only apply to Windows 10 (not mobile). Please add information regarding the mobile version.

Additionally, which prerequisites are required? Is o365 mdm sufficient or are full intune licenses needed?

**Comment by TrudyHa** [comment]
@imfgmbh  ... Thanks for the feedback. We're looking at making updates to clarify the experience on Windows 10 vs Windows 10 Mobile.

**Comment by imfgmbh** [comment]
Still no update, very unclear for o365 Business users, whether you need extra tools or not (e.g. EMs or intune)

**Comment by TrudyHa** [comment]
@imfgmbh ... To address your questions ... 
- MDM is supported for Windows 10 and Windows 10 Mobile
- Group Policy support is only for Windows 10 (and Server 2016 - for this GPO listed in the topic) 
- O365 MDM -- This program is aimed at managing access to Excahnge accounts, and doesn't support the RequirePrivateStoreOnly attribute: https://msdn.microsoft.com/en-us/library/windows/hardware/dn904962.aspx#ApplicationManagement_RequirePrivateStoreOnly 
 You can learn more here: https://support.office.com/en-us/article/Capabilities-of-built-in-Mobile-Device-Management-for-Office-365-a1da44e5-7475-4992-be91-9ccec25905b0?ui=en-US&rs=en-US&ad=US#bkmk_policysettings  
and
https://support.office.com/en-us/article/Choose-between-MDM-for-Office-365-and-Microsoft-Intune-c93d9ab9-efb2-4349-9b93-30c30562ee22?ui=en-US&rs=en-US&ad=US 

Updates are coming to clarify which OS versions are supported for MDM and GP.
