### ISSUE TITLE
Applocker / Publisher Rules / Evaluation & Trust unclear

### ISSUE THREAD

**Issue by mschilt** [Microsoft/windows-itpro-docs#40]
The explanation of publisher rules at 
windows-itpro-docs/windows/keep-secure/understanding-applocker-rule-condition-types.md 
and https://technet.microsoft.com/itpro/windows/keep-secure/understanding-the-publisher-rule-condition-in-applocker
is a bit unclear: 

* Does the .exe file have to be 'trusted' of just be 'signed'?
* The applocker xml policy just contains strings of certificate properties (name, issuer, .. ). So I am assuming applocker does not actually check the validity itself otherwise at least a fingerprint of the signing CA would be in the policy and its hard to believe that you guys just do a string comparison.
* Are publisher rules related to AppID (for checking signature validity)?
* To which filetypes does it apply? 

thanks for clarification.

**Comment by brianlic-msft** [comment]
@mschilt Here are some answers to your questions.  Thanks!

- Publisher rules only apply to digitally signed files.
- We ensure that the signature is valid and that the certificate is trusted in the trusted root store.
- For UWP apps, we rely on the App ID information that is signed as part of the signature.
- Publisher rules apply to all that file types that are supported by AppLocker in its rule collections. Some script file types (e.g. .bat and .cmd) do not support embedded signatures but they can be signed by using catalog files.

**Comment by mschilt** [comment]
Thanks Brian. Exactly what I was looking for.
