### ISSUE TITLE
bad commands for creating logs share

### ISSUE THREAD

**Issue by jdravet** [Microsoft/windows-itpro-docs#44]
Currently the document has
Create and share the E:\Logs folder by running the following commands in an elevated Windows PowerShell prompt: syntax New-Item -Path E:\Logs -ItemType directory New-SmbShare ?Name Logs$ ?Path E:\Logs -ChangeAccess EVERYONE icacls E:\Logs /grant '"MDT_BA":(OI)(CI)(M)'

It should read:
Create and share the E:\Logs folder by running the following commands in an elevated Windows PowerShell prompt:
New-Item -Path E:\Logs -ItemType directory 
New-SmbShare -Name Logs$ -Path E:\Logs -ChangeAccess EVERYONE
icacls E:\Logs /grant '"MDT_BA":(OI)(CI)(M)'

**Comment by brianlic-msft** [comment]
@jdravet Which document is this?

**Comment by jdravet** [comment]
https://technet.microsoft.com/en-us/itpro/windows/deploy/prepare-for-windows-deployment-with-mdt-2013

**Comment by brianlic-msft** [comment]
Thanks for reporting this!  It was a formatting error in the source and is now fixed.
