### ISSUE TITLE
Will this documentation be implemented into docs.microsoft.com?

### ISSUE THREAD

**Issue by Borkason** [Microsoft/windows-itpro-docs#46]
It seems very odd that Microsoft presents docs.microsoft.com and then actively builds a new repository for Windows 10 IT professionals.

I'd like to ask if this repository will be incorporated into docs.microsoft.com any time in the future? If this would not be the case would there a specific reason? Just asking out of curiousity.

Thank you.

**Comment by brianlic-msft** [comment]
@Borkason Thanks for the feedback!  docs.microsoft.com and the Windows 10 repo were built around the same time so the schedules didn't align. We are looking into a migration to docs.microsoft.com in the future though.
