### ISSUE TITLE
Collect data using Enterprise Site Discovery - Windows 10 script missing

### ISSUE THREAD

**Issue by alexverboon** [Microsoft/windows-itpro-docs#48]
The "C:\temp\iesite\Enterprise Site Discovery v2.1.zip" only contains scripts for Windows 7 and Windows 8, but the article mentions (IETelemetrySetUp.ps1 which does not exist. 

What script must be used to turn on IE11 site discovery on Windows 10 clients?

Reference article: Collect data using Enterprise Site Discovery
library
https://technet.microsoft.com/en-us/itpro/internet-explorer/ie11-deploy-guide/collect-data-using-enterprise-site-discovery?lc=1033

**Comment by eross-msft** [comment]
I've looked into this a bit, but I don't yet have a definitive response as it keeps getting passed around for more detailed info. The current thinking by the software engineer is this: 
IETElemetrySetUp-Win7.ps1 and IETElemetrySetUp-Win8.ps1 are one and the same, except that Win7 needed SHA1 signing and Win8 (and above?) needed SHA2. I just downloaded the .zip and confirmed using Windiff tool that the only difference between these two were the signatures. I believe that the Win8 script will work with IE11 on Win10 too, but this needs to be tested.
