### ISSUE TITLE
URL https://settings-win.data.microsoft.com/settings missing?

### ISSUE THREAD

**Issue by alexverboon** [Microsoft/windows-itpro-docs#50]
Based on our network traces, it looks like https://settings-win.data.microsoft.com/settings i also used, however this URL isn't listed in the article.

**Comment by brianlic-msft** [comment]
@alexverboon Do you mean [this](https://technet.microsoft.com/en-us/itpro/windows/manage/configure-windows-telemetry-in-your-organization) article? If not, can you list the file?

**Comment by alexverboon** [comment]
Hi Brian, no https://technet.microsoft.com/en-us/itpro/windows/deploy/upgrade-analytics-get-started this one, but I see it's listed there, not sure if it was before, if so my apologies, we must haver overlooked it. However I have another question,  without manually configuring winhttp via netsh the checking connection would not work, i.e. we had to hardcode the proxy for the script to succeed. Can you share any more details / prerequisites for clients behind a proxy? We are normally using a PAC proxy configuration file for the regular user, but unfortunately not for the system account, and we rather would not like that we have to configure the winhttp proxy statically.

**Comment by brianlic-msft** [comment]
@alexverboon We released a KB on 10/11 that might help.  Have a look at: https://support.microsoft.com/en-us/kb/3192441
