### ISSUE TITLE
Drivers for Windows 10 Reference Image

### ISSUE THREAD

**Issue by mikesmithwsu** [Microsoft/windows-itpro-docs#57]
You briefly talk about drivers for the reference image.  But, when you're talking about the drivers, you're only talking about how you don't have to worry about them because you're building the image in Hyper-V.  (And that all makes sense).

I'm trying to figure out how and where drivers are supposed to be when my Windows 10 reference image is turning on post sysprep.  
I am building an HP EliteBook 850 G3.  HP has all the windows 10 drivers available.  In windows 7, I would typically just place the drivers into the "c:\windows\inf" folder, and because of the DevicePath registry, the OS would automatically look there to find its drivers post SysPrep.  I've checked in Windows 10, the DevicePath registry still exists, but, when I put the drivers there, it doesn't find all the drivers.  When the OS is finished with the boot process, I can go do device manager, update the driver by pointing it to the c:\windows\inf folder, and it finds the drivers immediately.  So, I know the drivers are there, and work.  
We also have these drivers on a network share.  So, I created an unattend.xml that I incorporated with sysprep.  This unattend.xml pointed the image to look out at a network share for the driver files.  This didn't help either.  
Is there any other specific way I should be handling drivers when building a reference image?  I am wanting to build one image, that works on multiple hardware models.  

Thanks.

Mike

**Comment by brianlic-msft** [comment]
@mikesmithwsu You'll probably have better luck posting this in the [Installation, Setup, and Deployment](https://social.technet.microsoft.com/forums/en-us/home?forum=win10itprosetup) support forum.
