### ISSUE TITLE
URL Link is incorrect

### ISSUE THREAD

**Issue by andrewbettany** [Microsoft/windows-itpro-docs#58]
In the main article, you mention: Free upgrade: The Windows 10 free upgrade offer expired on July 29, 2016. For more information, see Free upgrade paths.

The link to "Free upgrade paths"redirects to this page and does not provide the reader with any new information.

I suggest it is redirected to the "Upgrade to Windows 10: FAQ" page here: https://support.microsoft.com/en-us/help/12435/windows-10-upgrade-faq

**Comment by brianlic-msft** [comment]
@andrewbettany Thanks for reporting this!  Do you have a link to the main article?  When an issue is opened, it doesn't tell us which page.

**Comment by andrewbettany** [comment]
Sure: 
https://technet.microsoft.com/en-us/itpro/windows/deploy/windows-10-upgrade-paths#Free-upgrade-paths

**Comment by greg-lindsay** [comment]
The link brings you to a section on the same page, at the bottom where you can read about the free upgrade offering if you are curious about what was offered.  The FAQ link you suggested is also there. I think there is new information provided, so I don't see a problem with the link.
