### ISSUE TITLE
Typo on live site

### ISSUE THREAD

**Issue by adamsampson** [Microsoft/windows-itpro-docs#60]
https://technet.microsoft.com/en-us/itpro/windows/deploy/activate-using-active-directory-based-activation-client

The bottom of the page references  "slmrg.vbs /dlv" instead of  "slmgr.vbs /dlv".  The version here on github appears correct.

**Comment by greg-lindsay** [comment]
Thanks for catching this. I've fixed it in the repository and it will go live when the next push happens.
