### ISSUE TITLE
Adding AAD users doesn't work

### ISSUE THREAD

**Issue by stefanfritsch** [Microsoft/windows-itpro-docs#66]
Hi,

the following

    Enter Authenticated Users, then click Check Names. If the Name Not Found window opens, click Locations and select this PC.

doesn't work. Not even my own user appears in the list, never mind anyone else from Azure AD. I tried email, AzureAD\UserName and just UserName. They also don't appear in the list of objects (which is less surprising).

Could you please expand your guide to explain what you actually mean and how I'm supposed to add User.Name@contoso.com?

Both computers are running 1607, I just checked.

Thx
Stefan

**Comment by brianlic-msft** [comment]
@stefanfritsch In which file did you see this?  Thanks!

**Comment by stefanfritsch** [comment]
In 
https://github.com/Microsoft/windows-itpro-docs/blob/master/windows/manage/connect-to-remote-aadj-pc.md

Sorry, didn't realize the repo contained all the documentation

**Comment by brianlic-msft** [comment]
@jdeckerMS can you take a look?

**Comment by jdeckerMS** [comment]
hi Stefan, to make this work, you add the local group "Authenticated Users" (step 4). You can't specify specific Azure AD accounts.

**Comment by stefanfritsch** [comment]
Actually, you can.

The user has to log in locally first to get the SID on the Computer, then use

    net localgroup "Remote Desktop Users" /add "AzureAD\FirstnameLastname"

It would be nice if you could add that to the guide.

**Comment by jdeckerMS** [comment]
Thanks, Stefan, I've added that to my task list to investigate.
