### ISSUE TITLE
WMIC and Setting the MDT Driver Path

### ISSUE THREAD

**Issue by randytho** [Microsoft/windows-itpro-docs#81]
Regarding the portion of the article: 

> The preceding folder names are selected because they match the actual make and model values that MDT reads from the machines during deployment. You can find out the model values for your machines via the following command in Windows PowerShell:
> 
> Get-WmiObject -Class:Win32_ComputerSystem
> Or, you can use this command in a normal command prompt:
> 
> wmic csproduct get name

Prior to update 2, I have used the command `wmic computersystem get model` and manufacturer to build the MDT folders in out of box drivers. With the latest PE litetouch I am not getting the same result back from WMIC and therefore my driver injection is failing.  I have verified the difference in output by booting from an old boot media created prior to update 2 and issuing the command from a prompt. I will attach screens of the wmic computersystem list output on the two versions. You mention csproduct. Is this a functional change from the previous MDT releases?
![2013 update 2](https://cloud.githubusercontent.com/assets/24234376/20686445/50a01542-b57e-11e6-9d12-b502920d3bf7.jpg)
![2013](https://cloud.githubusercontent.com/assets/24234376/20686444/509f83fc-b57e-11e6-91c2-c45313818a65.jpg)

**Comment by randytho** [comment]
This is the issue: https://social.technet.microsoft.com/Forums/en-US/9a9cc1ba-d6f2-4e20-841d-c8b809647b66/windows-mdt-2013-update-1-injecting-driver-problems?forum=mdt&prof=required

**Comment by brianlic-msft** [comment]
@randytho If you are still having problems, you should contact Microsoft Support.  Thanks!
