### ISSUE TITLE
Device Account info can't be found. Make sure the device account is setup (0x80FF009)

### ISSUE THREAD

**Issue by mfahadjalil** [Microsoft/windows-itpro-docs#88]
Hello Guys,
Please help me solve the following error while configuring Microsoft Surface Hub.

**Device Account info can't be found. Make sure the device account is setup (0x80FF0009)**

Thanks!!

![img_20161214_155435](https://cloud.githubusercontent.com/assets/24590162/21229575/aa52bcda-c2a7-11e6-9404-90543613329e.jpg)

**Comment by mfahadjalil** [comment]
Sorry for type, Error Code is 0x80FF0009

**Comment by jdeckerMS** [comment]
Hello mfahadjalil, the best way to get help configuring your Surface Hub is by contacting Surface Hub support. Start at this page: [Microsoft Surface Hub](https://www.microsoft.com/surface/en-us/support/surface-hub).
