### ISSUE TITLE
WMI filters for Windows 10 

### ISSUE THREAD

**Issue by alexverboon** [Microsoft/windows-itpro-docs#90]
The article says:

•Windows 10
•Windows Server 2016

But the article doesn't contain any examples for Windows 10 nor Server 2016, can this be added please?

**Comment by brianlic-msft** [comment]
@alexverboon Can you list the file where you're seeing this?

**Comment by alexverboon** [comment]
Hi, here's the link
https://technet.microsoft.com/en-us/itpro/windows/keep-secure/create-wmi-filters-for-the-gpo

It only shows Windows 8 and server 2012 examples

Cheers
Alex

**Comment by Justinha** [comment]
Thanks for the suggestion Alex. I changed the examples to Windows 10 and Windows Server 2016.
