### ISSUE TITLE
Is this actually real? 

### ISSUE THREAD

**Issue by JerodPowell** [Microsoft/windows-itpro-docs#92]
Microsoft is targeting Windows 10 Enterprise E3 for small biz and in some places says for as little as one user but then recommends 50.  My issue is a user must have windows 10 pro anniversary update before they can even leverage he Windows 10 Enterprise E3 license?  I have combed the web and Microsoft site for a different answer and this was all I could find that definitely said, Azure AD joined and Windows 10 Pro Anniversary update or the subscription is effectively useless.  Many other texts elude to the fact that you can upgrade other OS's.  If this is absolutely the case then wow, epic fail and very disappointing to say the least. Basically if you can't provide a surface with it or hardware refresh then what is the value, effectively 0.

**Comment by eross-msft** [comment]
You are correct, Windows 10 Pro version 1607 is a prerequisite. For more information, see https://docs.microsoft.com/en-us/windows/deployment/windows-10-enterprise-e3-overview.
