### ISSUE TITLE
Start Menu Customization Documentation Updates for Win10 1607

### ISSUE THREAD

**Issue by DLAtWork** [Microsoft/windows-itpro-docs#93]
We've found an issue with the Export-StartLayout commandlet in 1607 when you have .URL files pinned to the Start menu as tiles that should be addressed or documented.

In 1511 if you pinned a .URL shortcut from "All Apps" to the Start menu, then exported the layout via Export-StartLayout the resulting XML file would contain an entry like this:

`<start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationID="http://contoso.com" />`

Assuming there was a .URL file in the legacy Start menu folder structure with a matching web address this tile would appear correctly when used via LayoutModification.XML or the Win10 "Start Layout" GPO.

However, in 1607 if you perform the same steps, pin a .URL shortcut from "All Apps" to the Start menu, then export the layout via Export-StartLayout, the resulting XML file would contain an entry like this:

`<start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Contoso.com.url" />`

Note the different XML attribute used in 1607, "DesktopApplicationLinkPath", vs. 1511, "DesktopApplicationID". Additionally the 1607 exported value is the path to the .URL file itself, not the actual web address being referenced, as in the 1511 export.

The undocumented issue we've discovered is that neither 1511 nor 1607 will accept the DesktopApplicationLinkPath path to the URL file when building the Start menu at login and those Start tile entries simply won't appear. The tiles fail to appear with either the LayoutModification.xml or Win10 GPO settings. Changing the DesktopApplicationLinkPath value from the .URL file path back to the actual web address, and clearing the Start tile cache of profiles that are already affected, will resolve this issue.

Essentially we end up with an entry like this that works in 1607:
`<start:DesktopApplicationTile Size="2x2" Column="0" Row="0" DesktopApplicationLinkPath="http://contoso.com" />`

We're not sure if this is a bug in the 1607 Export-StartLayout commandlet or a bug in how Win10 reads in these XML files but the Start Menu customization documentation should be updated to reflect this issue.

We've also found that 1607 will usually read in Start layout XML files exported from 1511 without issues. However, if you take a 1607 system that was customized with a 1511 Start layout XML file and then export the 1607 Start layout, the XML tile entries will be converted from DesktopApplicationID to DesktopApplicationLinkPath in most cases. Apparently there's something behind the scenes in the 1607 Export-StartLayout commandlet that prefers local shortcut paths to registered application IDs.

**Comment by jdeckerMS** [comment]
Thanks for bringing this to our attention. I've forwarded your comments to the engineering team to review and determine what changes need to be made to the documentation.

**Comment by jdeckerMS** [comment]
A bug has been opened and the engineering team is investigating. I don't have a time estimate of when they'll complete this action.

**Comment by DLAtWork** [comment]
Thanks Jeanie, your work is much appreciated.

In working further on customizing our Win10 1607 Start menu XML layout for kiosk use we've also found... oddities in how Win10 handles redirected Start menu shortcuts and pinned tiles. Briefly a LNK shortcut has to exist in both the local ALLUSERSPROFILE Start menu directory structure AND in the redirected Start menu directory for the pinned tile to appear correctly with the "Hide common program groups" GPO setting enabled. Also in this setup,, while the Start menu seems to verify the existence of the LNK file based on the ALLUSERSPROFILE shortcut it pulls the actual tile info from the redirected LNK file. I can go into more detail if you think the engineering team would be interested.

I'm not going to lie, this new Win10 Start menu is extremely frustrating to work with in our higher ed lab environment. Moving shortcut files around in Win7 via script or GPPs was much, much easier comparatively.

**Comment by jdeckerMS** [comment]
I've added your additional information to the bug for the engineering team, thank you! I'll get in touch here if they ask for more details. :)
