### ISSUE TITLE
In Exchange on-prem setup issue

### ISSUE THREAD

**Issue by mohanse** [Microsoft/windows-itpro-docs#99]
In Exchange on-prem setup from (https://technet.microsoft.com/en-us/itpro/surface-hub/hybrid-deployment-surface-hub-device-accounts)

Unable to enable RoommailboxAccount in EXO for the federated account

Set-Mailbox 'HUB01@contoso.com' -RoomMailboxPassword $credNewAccount.Password -EnableRoomMailboxAccount $true

![capture](https://cloud.githubusercontent.com/assets/24958307/21717782/28d00b20-d40b-11e6-997c-2c8b209536ab.JPG)

**Comment by jdeckerMS** [comment]
Thanks for providing this information. I'll pass it on to the engineering team to investigate if changes to the topic are needed. Sorry that I can't provide an estimate for when any changes will be made.

**Comment by Steltek** [comment]
Same problem here. You can't set those in EXO, and you can't set the on-prem either as Set-RemoteMailbox does not have the -RoomMailboxPassword and -EnableRoomMailboxAccount parameters.

**Comment by jdeckerMS** [comment]
The engineering team has verified the steps work generally, but as mentioned in the topic, there are many variations possible in a specific environment/topology. For assistance, please contact Microsoft Support (https://www.microsoft.com/surface/en-us/support/contact-us-business-surface-hub).
